// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using desafio_magalu.Data;

#nullable disable

namespace desafio_magalu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114215324_Criando a tabela Schedulings")]
    partial class CriandoatabelaSchedulings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("desafio_magalu.Models.SchedulingModel", b =>
                {
                    b.Property<int>("IdScheduling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeOfSubmission")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stats")
                        .HasColumnType("int");

                    b.HasKey("IdScheduling");

                    b.ToTable("Schedulings");
                });
#pragma warning restore 612, 618
        }
    }
}
